version: "3.8"

services:
  pokemon-api:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - NODE_ENV=production
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - DATABASE_URL=file:/app/data/dev.db
    volumes:
      - ./data:/app/data
      - ./prisma:/app/prisma
    command: >
      sh -c "
        apt-get update && 
        apt-get install -y openssl curl sqlite3 && 
        mkdir -p /app/data && 
        touch /app/data/dev.db && 
        chmod 777 /app/data /app/data/dev.db && 
        npx prisma generate && 
        npx prisma migrate deploy && 
        npm start
      "
    stop_grace_period: 1m
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
